dom-creation - Susana Gutierrez
Susana-Gutierrez/m1-0621-code-solutions pull request #51
Opened 2021-08-10 04:47 UTC by Susana-Gutierrez

![dom-creation](https://user-images.githubusercontent.com/82625148/128809748-9379fcb2-3f69-4041-850c-5a3a650c76f6.JPG)

2021-08-10 17:05 UTC, BrettAlbright requested changes
small update needed!

2021-08-10 17:05 UTC, Zhiwutian commented on dom-creation/main.js
> +  document.querySelector('.row').appendChild(elementDiv);
so the one thing to update is to move the appending to the DOM to outside of the function. The `renderPokemon` function should only create and return the DOM tree, not append it to the DOM. 

You want to append each completed DOM tree to the DOM within the loop.

2021-08-11 04:13 UTC, Zhiwutian approved these changes
👍🏼

2021-08-11 04:13 UTC, Susana-Gutierrez commented
Changes were completed.
![dom-creation-2](https://user-images.githubusercontent.com/82625148/128968665-1f2c9e23-0353-4acf-8311-6865df72171a.JPG)

2021-08-11 04:14 UTC, merged